# Estágio 1: Build
FROM node:24-alpine AS builder
WORKDIR /app
COPY ./web/package*.json ./
RUN npm install
COPY ./web .
RUN npm run build

# Estágio 2: Produção
FROM node:24-alpine
WORKDIR /app
COPY --from=builder /app/.output ./.output
# Instale dependências de produção que possam ser necessárias, como o 'sharp'
RUN npm install sharp

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
