FROM golang:1.25-alpine

RUN apk add --no-cache build-base

WORKDIR /app

RUN go install github.com/air-verse/air@latest
COPY api/go.mod api/go.sum ./

# Baixa as dependências do projeto.
RUN go mod download

COPY ./api/ .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]